plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.5.1'
}

group = 'yanny'
version = '1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'yanny.ui.Yanny'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('shadowJar') {
    archiveFileName = 'yanny.jar'
    manifest {
        attributes 'Main-Class': 'yanny.ui.Yanny'
    }
}
